accounts/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup')
]

annotation/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'annotation'
urlpatterns = [
    path('', views.index, name='index'),
    path('error', views.error, name='error'),
    path('add_point_annotation', views.add_point_annotation, name='add_point_annotation'),
    path('add_segment_annotation', views.add_segment_annotation, name='add_segment_annotation'),
    path('add_video', views.add_video, name='add_video'),
    path('add_tools', views.add_tools, name='add_tools'),
    path('output_csv/', views.output_csv, name='output_csv'),
    path('output_csv/<slug:video_name>', views.output_csv, name='output_csv'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

svat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import urls as auth_urls
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('annotation/', include('annotation.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include(auth_urls)),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        
        {% block css %}
        <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
        {% endblock %}
        <title>SVAT</title>
    </head>

    <body>

        <header>


            <div>
                {% if user.is_superuser %}
                    <a class='logobutton' href="{% url 'annotation:index' %}">Surgical Video Annotation Tool</a>
                    <a class='topbutton' href="{% url 'logout' %}">Log Out</a>
                    <a class='topbutton' href="/admin">Admin Page</a>
                    <a class='topbutton' href="{% url 'annotation:index' %}">Annotation Page</a>
                {% elif user.is_authenticated %}
                    <a class='logobutton' href="{% url 'annotation:index' %}">Surgical Video Annotation Tool</a>
                    <a class='topbutton' href="{% url 'logout' %}">Log Out</a>
                    <a class='topbutton' href="{% url 'annotation:index' %}">Annotation Page</a>

                {% else %}
                    <a class='logobutton' >Surgical Video Annotation Tool</a>
                    <a class='topbutton' href="{% url 'login' %}">Log In</a>
                    <a class='topbutton' href="{% url 'accounts:signup' %}">Sign Up</a>
                {% endif %}
            </div>
        </header>
        {% block content %}
        {% endblock %}
        <footer>

        </footer>
    </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block css %}{{block.super}}
{% endblock %}
{% block content %}
{% load static %}
    
<h1 id='hometitle'>Welcome to the Surgical Video Annotation Tool!</h1>

{% endblock %}