annotation/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'annotation'
urlpatterns = [
    path('', views.index, name='index'),
    path('error', views.error, name='error'),
    path('add_point_annotation', views.add_point_annotation, name='add_point_annotation'),
    path('add_segment_annotation', views.add_segment_annotation, name='add_segment_annotation'),
    path('add_video', views.add_video, name='add_video'),
    path('add_tools', views.add_tools, name='add_tools'),
    path('output_csv/', views.output_csv, name='output_csv'),
    path('output_csv/<slug:video_name>', views.output_csv, name='output_csv'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

svat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import urls as auth_urls
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('annotation/', include('annotation.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include(auth_urls)),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

annotation/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import FileExtensionValidator
from datetime import datetime
from django.conf import settings
import os
import csv
import json
from io import StringIO

class Video(models.Model):
    video = models.FileField() #validators=[FileExtensionValidator(allowed_extensions=['mp4, mov'])]
    video_timestamp = models.FloatField(null=True)

    def __str__(self):
        return self.video.name

    def set_timestamp(self, time):
        self.video_timestamp = time
        self.save()

class Tools(models.Model):
    tools = models.CharField(max_length=1000, null=True, blank=True) #TODO: is this right
    tools_video = models.ForeignKey('Video', on_delete=models.CASCADE, null=True, blank=True) #TODO: review this to see if correct delete method
    tools_file = models.FileField(upload_to='tools', null=True)
    tools_video_indicator = models.CharField(max_length=200, null=True, blank=True)

    def set_tools(self, t):
        self.tools = json.dumps(t)

    def get_tools(self):
        return json.loads(self.tools)

    def save(self, *args, **kwargs):
        read_tools_file = self.tools_file.read().decode('utf-8')
        tools = read_tools_file.rstrip('\n') .split(',')
        self.set_tools(tools)
        self.tools_video = Video.objects.filter(video=self.tools_video_indicator)[0]
        super(Tools, self).save(*args, **kwargs) #Call the "real" save() method.

class PointAnnotation(models.Model):
    point_annotation_video = models.ForeignKey('Video', on_delete=models.CASCADE, null=True, blank=True) #TODO: discuss delete method
    point_annotation_tool = models.CharField(max_length=200, blank=True) #TODO: is this behavior correct? if toolset deleted, then just replace toolset with null?   
    point_annotation_timestamp = models.FloatField(null=True)
    point_annotation_video_indicator = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.point_annotation_tool

    def save(self, *args, **kwargs):
        self.point_annotation_video = Video.objects.filter(video=self.point_annotation_video_indicator)[0]
        super(PointAnnotation, self).save(*args, **kwargs) #Call the "real" save() method.

class SegmentAnnotation(models.Model):
    segment_annotation_video = models.ForeignKey('Video', on_delete=models.CASCADE, null=True, blank=True) #TODO: discuss delete method
    segment_annotation_text = models.CharField(max_length=200, blank=True)
    segment_annotation_starttime = models.FloatField(null=True)
    segment_annotation_endtime = models.FloatField(null=True)
    segment_annotation_video_indicator = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.segment_annotation_text

    def save(self, *args, **kwargs):
        self.segment_annotation_video = Video.objects.filter(video=self.segment_annotation_video_indicator)[0]
        super(SegmentAnnotation, self).save(*args, **kwargs) #Call the "real" save() method.

annotation/forms.py
from django import forms
from .models import Video, Tools, PointAnnotation, SegmentAnnotation
from django.core.exceptions import ValidationError
from django.conf import settings
from django.utils.text import get_valid_filename
import os

class PointAnnotationForm(forms.ModelForm):
    class Meta:
        model = PointAnnotation
        exclude = ['point_annotation_video']

class SegmentAnnotationForm(forms.ModelForm):
    class Meta:
        model = SegmentAnnotation
        exclude = ['segment_annotation_video']

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        exclude = []
    
    def __init__(self, *args, **kwargs):
        super(VideoForm, self).__init__(*args, **kwargs)
        self.fields['video'].widget.attrs.update({'class' : 'uploadbutton'})

    def clean_video(self):
        vid = self.cleaned_data['video']
        limit = 5 * 1024 * 1024 * 1024
        vid.name = get_valid_filename(vid.name)
        if vid.size > limit:
            raise ValidationError('File too large. Size should not exceed 5 Gb.')
        if vid.name in os.listdir(settings.MEDIA_ROOT):
            raise ValidationError('Video already uploaded.')
        return vid

class ToolsForm(forms.ModelForm):
    class Meta:
        model = Tools
        exclude = []

    def clean_tools_file(self):
        tf = self.cleaned_data['tools_file']
        tf.name = get_valid_filename(tf.name)
        return tf

annotation/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpResponseBadRequest
from django.template import loader
from django.urls import reverse
from datetime import datetime
from .models import Tools, Video, PointAnnotation, SegmentAnnotation
from .forms import PointAnnotationForm, SegmentAnnotationForm, VideoForm, ToolsForm
from django.conf import settings
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
import csv
import os

@login_required
def index(request):   
    point_annotation_model_form = PointAnnotationForm()
    segment_annotation_model_form = SegmentAnnotationForm()     
    video_model_form = VideoForm()
    video_list = Video.objects.all()
    tools_model_form = ToolsForm()
    try:
        available_video = Video.objects.get(video=[f for f in os.listdir(settings.MEDIA_ROOT) if f != 'tools'][0])
        annotation_list = list(PointAnnotation.objects.filter(point_annotation_video=available_video)) + \
                            list(SegmentAnnotation.objects.filter(segment_annotation_video=available_video)) #TODO: change this concatenation to merge
        annotation_list.sort(key=lambda t: t.point_annotation_timestamp if 'point_annotation_timestamp' in str(t._meta.get_fields()) else t.segment_annotation_starttime)
    except (Video.DoesNotExist, IndexError, Video.MultipleObjectsReturned) as e:
        available_video = None
    try:
        tools = [t.get_tools() for t in Tools.objects.filter(tools_video=available_video)][-1]
    except:
        tools = None
    try:
        if not Video.objects.all().exists():
            for f in [f for f in os.listdir(settings.MEDIA_ROOT) if f != 'tools']:
                os.remove(os.path.join(settings.MEDIA_ROOT, f))
    except:
        pass

    if available_video:
        context = {
            'annotation_list': annotation_list,
            'point_annotation_model_form': point_annotation_model_form,
            'segment_annotation_model_form': segment_annotation_model_form,
            'video_model_form': video_model_form,
            'tools_model_form': tools_model_form,
            'video_list': video_list,
            'tools': tools,
            'available_video': available_video,
        }
    else:
        context = {
            'point_annotation_model_form': point_annotation_model_form,
            'segment_annotation_model_form': segment_annotation_model_form,
            'video_model_form': video_model_form,
            'tools_model_form': tools_model_form,
        }
    return render(request, 'annotation/index.html', context)

@login_required
def add_point_annotation(request):
    if request.method == 'POST':
        aForm = PointAnnotationForm(request.POST) 
        print(aForm)
        if aForm.is_valid():
            indicator = aForm.cleaned_data['point_annotation_video_indicator']
            Video.objects.filter(video=indicator)[0].set_timestamp(aForm.cleaned_data['point_annotation_timestamp'])
            aForm.save()
            return redirect('annotation:index')
        else:
            point_annotation_errors = aForm.errors
            point_annotation_model_form = PointAnnotationForm()
            context = {'point_annotation_errors': point_annotation_errors, 'point_annotation_model_form': point_annotation_model_form}
            return render(request, 'annotation/index.html', context)

@login_required
def add_segment_annotation(request):
    if request.method == 'POST':
        aForm = SegmentAnnotationForm(request.POST) 
        if aForm.is_valid():
            indicator = aForm.cleaned_data['segment_annotation_video_indicator']
            Video.objects.filter(video=indicator)[0].set_timestamp(aForm.cleaned_data['segment_annotation_endtime'])
            aForm.save()
            return redirect('annotation:index')
        else:
            segment_annotation_errors = aForm.errors
            segment_annotation_model_form = SegmentAnnotationForm()
            context = {'segment_annotation_errors': segment_annotation_errors, 'segment_annotation_model_form': segment_annotation_model_form}
            return render(request, 'annotation/index.html', context)

@login_required
def add_video(request):
    if request.method == 'POST':
        vForm = VideoForm(request.POST, request.FILES)
        if vForm.is_valid():
            #NOTE: review this delete process
            for f in [f for f in os.listdir(settings.MEDIA_ROOT) if f != 'tools']:
                os.remove(os.path.join(settings.MEDIA_ROOT, f))
            if vForm.cleaned_data['video'].name in [ff.video.name for ff in Video.objects.all()]:
                path = default_storage.save(os.path.join(settings.MEDIA_ROOT, vForm.cleaned_data['video'].name), 
                                            ContentFile(vForm.cleaned_data['video'].read()))
                return redirect('annotation:index')
            vForm.save()
            return redirect('annotation:index')
        else:
            video_errors = vForm.errors
            video_model_form = VideoForm()
            context = {'video_errors': video_errors, 'video_model_form': video_model_form}
            return render(request, 'annotation/error.html', context)

@login_required
def add_tools(request):
    if request.method == 'POST':
        tForm = ToolsForm(request.POST, request.FILES)
        if tForm.is_valid():
            toolspath = os.path.join(settings.MEDIA_ROOT, 'tools')
            for f in os.listdir(toolspath):
                os.remove(os.path.join(toolspath, f))
            tForm.save()
            return redirect('annotation:index')
        else:
            tools_errors = tForm.errors
            tools_model_form = ToolsForm()
            context = {'tools_errors': tools_errors, 'tools_model_form': tools_model_form}
            return render(request, 'annotation/error.html', context)

@login_required
def output_csv(request, *args, **kwargs):
    if request.method == 'POST':
        video_slug = kwargs['video_name']
        slug_dict = dict(zip([slugify(v.video.name) for v in Video.objects.all()], [v.video.name for v in Video.objects.all()]))
        video = Video.objects.get(video=slug_dict[video_slug]) #NOTE: this relies on all video names correspoding to unique slugs (important assumption)
        fname = str(video).split('.')[0]
        response = HttpResponse(
            content_type='text/csv',
            headers={'Content-Disposition': 'attachment; filename="{fname}.csv"'.format(fname=fname)},
        )
        writer = csv.writer(response)
        writer.writerow(['video', 'annotation_type', 'point_timestamp', 'segment_start', 'segment_end', 'point_tool', 'segment_text'])

        points = PointAnnotation.objects.filter(point_annotation_video=video)
        segments = SegmentAnnotation.objects.filter(segment_annotation_video=video)
        data = list(points) + list(segments)
        data.sort(key=lambda t: t.point_annotation_timestamp if 'point_annotation_timestamp' in str(t._meta.get_fields()) else t.segment_annotation_starttime)
        for d in data:
            if isinstance(d, PointAnnotation):
                writer.writerow([d.point_annotation_video, 'point', d.point_annotation_timestamp, '', '', d.point_annotation_tool, ''])
            else:
                writer.writerow([d.segment_annotation_video, 'segment', '', d.segment_annotation_starttime, d.segment_annotation_endtime, '', d.segment_annotation_text])

    return response


@login_required
def error(request):
    context = {}
    return render(request, 'annotation/error.html')

annotation/templates/annotation/error.html
{% extends "base.html" %}
{% block content %}

    <h1 class='error'>Error. Go back to <a href="{% url 'annotation:index' %}">Annotation Page</a></h1>
    
    {% if video_errors %}
        <h1>{{video_errors.video}}</h1>
    {% endif %}

    {% if annotation_errors %}
        {{annotation_errors}}
    {% endif %}

    {% if tools_errors %}
        {{tools_errors}}
    {% endif %}
{% endblock %}

annotation/templates/annotation/index.html
{% extends "base.html" %}
{% block css %}{{block.super}}
<link rel="stylesheet" href="{{ STATIC_URL }}css/annotation.css">
{% endblock %}
{% block content %}
{% load static %}

<div class="row">
    <div class="column">
        <link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet" />
        <script src="{% static 'js/annotation.js' %}"></script>
        {% if available_video %}
        <!-- VIDEO PLAYER -->
            <div class='video'>
                <video
                    id="my-video"
                    class='video-js vjs-big-play-centered'
                    controls
                    preload="auto"
                    autoplay
                    muted
                    width="640"
                    height="360"
                    data-setup="{}"
                >
                    <source src='{{MEDIA_URL}}{{available_video}}' type="video/mp4" />
                    <source src='{{MEDIA_URL}}{{available_video}}' type="video/webm" />
                    <p class="vjs-no-js">
                    To view this video please enable JavaScript, and consider upgrading to a
                    web browser that
                        <a href="https://videojs.com/html5-video-support/" target="_blank"
                            >supports HTML5 video</a
                        >
                    </p>
                </video>
                <script src="https://vjs.zencdn.net/7.11.4/video.min.js"></script>
                <script src="//cdn.sc.gl/videojs-hotkeys/latest/videojs.hotkeys.min.js"></script>
                <script src="{% static '/js/videojs-rotatezoom/src/videojs.zoomrotate.js' %}" type="text/javascript"></script>  
                <script src="{% static '/js/rotate.js' %}" type="text/javascript"></script>  
                <script src="{% static '/js/zoom.js' %}" type="text/javascript"></script> 
                <script>
                    var myPlayer = videojs('my-video',{
                        'playbackRates': [0.25,0.5,0.75,1.0,1.5,2.0,2.5,3],
                        'plugins': {
                            'hotkeys':{
                                'enableModifiersForNumbers': false,
                            }
                        }
                    });
                    myPlayer.currentTime(parseFloat("{{available_video.video_timestamp}}"));
                    myPlayer.rotate(myPlayer);
                    myPlayer.zoom(myPlayer);
                </script>
            </div>
        {% endif %}
        
        <!-- VIDEO UPLOAD MODEL FORM -->
        <div class=uploadform>
            <h4>Select Video:</h4>
            {% if video_model_form %}
            {% if error_message %} <p><strong>{{error_message}}</strong></p> {% endif %}
            {% if video_errors %}{{video_errors}} {% endif %}
            <form class=videouploadform action="{% url 'annotation:add_video' %}"  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{video_model_form.non_field_errors}}
                <div class="fieldWrapper">
                    {{ video_model_form.video.errors }}
                    <label for="{{ video_model_form.video.id_for_label }}"></label>
                    {{ video_model_form.video }}
                </div>
                <div class="fieldWrapper">
                    {{ video_model_form.video_timestamp.errors }}
                    <input type="hidden" name="video_timestamp" id="id_video_timestamp" value=0>
                </div>
                <input type='submit' value='Add Video'/>
            </form>
            {% endif %}
        </div>

        <!-- TOOLS MODEL FORM -->
        {% if available_video %}
            <div class=uploadform>
                <h4>Select Tools File:</h4>
                {% if tools_model_form %}
                {% if error_message %} <p><strong>{{error_message}}</strong></p> {% endif %}
                {% if tools_errors %}{{tools_errors}} {% endif %}
                <form action="{% url 'annotation:add_tools' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{tools_model_form.non_field_errors}}
                    <div class="fieldWrapper">
                        {{ tools_model_form.tools_file.errors }}
                        <label for="{{ video_model_form.tools_file.id_for_label }}"></label>
                        {{ tools_model_form.tools_file }}
                    </div>
                    <div class="fieldWrapper">
                        {{ tools_model_form.tools_video_indicator.errors }}
                        <!-- <label for="{{ video_model_form.tools_video_indicator.id_for_label }}">Tools Video Indicator:</label> -->
                        <!-- {{ tools_model_form.tools_video_indicator }} -->
                        <input type="hidden" name="tools_video_indicator" id="id_tools_video_indicator" value="{{available_video}}">
                    </div>
                    <div class="fieldWrapper">
                        {{ tools_model_form.tools_video.errors }}
                        <input type="hidden" name="tools_video" id="id_tools_video" value="1">
                    </div>
                    <input type='submit' value='Add Tools File'/>
                </form>
                {% endif %}
            </div>

            <!-- ANNOTATION MODEL FORM -->
            <div>
                {% if point_annotation_model_form %}
                    {% if error_message %} <p><strong>{{error_message}}</strong></p> {% endif %}
                    {% if point_annotation_errors %}{{point_annotation_errors}} {% endif %}
                    {% if segment_annotation_errors %}{{segment_annotation_errors}} {% endif %}

                    <div>
                        <button id='timepoint_toggle' name='timepoint' class=annotationbutton onclick="showhide('timepoint'); playpause();">Time-Point Annotation</button>
                        <button id='timesegment_toggle' name='timesegment' class=annotationbutton onclick="showhide('timesegment'); timestamp('id_segment_annotation_starttime')";>Time-Segment Annotation</button>
                    </div>

                    <!-- POINT -->
                    <div id='timepoint' style='visibility:hidden;' class=hidden>
                        <form action="{% url 'annotation:add_point_annotation' %}" method="post">
                            {% csrf_token %}
                            {{point_annotation_model_form.non_field_errors}}
                            <div class="fieldWrapper">
                                {{ point_annotation_model_form.point_annotation_video_indicator.errors }}
                                <input type="hidden" name="point_annotation_video_indicator" id="id_point_annotation_video_indicator" value="{{available_video}}">
                            </div>
                            <div class="fieldWrapper">
                                {{ point_annotation_model_form.point_annotation_timestamp.errors }}
                                <input type="hidden" name="point_annotation_timestamp" id="id_point_annotation_timestamp">
                            </div>
                            <div class="fieldWrapper">
                                {{ point_annotation_model_form.point_annotation_tool.errors }}
                                <label for="{{ point_annotation_model_form.point_annotation_tool.id_for_label }}" class=uploadlabel>Annotation tool:</label>
                                <select name="point_annotation_tool" id="id_point_annotation_tool">
                                    <option value="" selected disabled>Select Tool</option>
                                    {% for tool in tools %}
                                        <option value="{{tool}}">{{tool}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <input type='submit' value='Save Annotation' onclick="timestamp('id_point_annotation_timestamp'); play();" class=submitannotation/>
                        </form>
                    </div>

                    <!-- SEGMENT -->
                    <div id='timesegment' style='visibility:hidden;' class=hidden>
                        <form action="{% url 'annotation:add_segment_annotation' %}", method="post">
                            {% csrf_token %}
                            {{segment_annotation_model_form.non_field_errors}}
                            <div class="fieldWrapper">
                                {{ segment_annotation_model_form.segment_annotation_video_indicator.errors }}
                                <input type="hidden" name="segment_annotation_video_indicator" id="id_segment_annotation_video_indicator" value="{{available_video}}">
                            </div>
                            <div class="fieldWrapper">
                                {{ segment_annotation_model_form.segment_annotation_text.errors }}
                                <label for="{{ segment_annotation_model_form.segment_annotation_text.id_for_label }}">Annotation text:</label>
                                {{ segment_annotation_model_form.segment_annotation_text }}
                            </div>

                            <div class="fieldWrapper">
                                {{ segment_annotation_model_form.segment_annotation_starttime.errors }}
                                <input type="hidden" name="segment_annotation_starttime" id="id_segment_annotation_starttime">
                            </div>
                            <div class="fieldWrapper">
                                {{ segment_annotation_model_form.segment_annotation_endtime.errors }}
                                <input type="hidden" name="segment_annotation_endtime" id="id_segment_annotation_endtime">
                            </div>
                            <!-- <button id='start' onclick="timestamp('id_segment_annotation_starttime'); ;">Start Segment</button> -->
                            <input type='submit' value='End and Save Segment Annotation' onclick="timestamp('id_segment_annotation_endtime')" class=submitannotation/>
                        </form>
                    </div>




                {% endif %}
            </div>


     </div>
    <div class="column">
            <!-- ANNOTATION DISPLAY -->
            <div class='annotationlist'>
                {% if annotation_list %}
                    <h3> List of Annotations </h3> 
                    <nav>
                        <ul>
                            {% for annotation in annotation_list %}
                            <li>{{error}}  {{annotation.point_annotation_tool}} {{annotation.segment_annotation_text}} {{annotation.point_annotation_timestamp}} {{annotation.segment_annotation_starttime}} {% if annotation.segment_annotation_starttime %}{{"-"}} {% endif %} {{annotation.segment_annotation_endtime}}</li>
                            {% endfor %}
                        </ul>
                    </nav>
                    {% else %}
                        <p>No annotations recorded. </p>
                {% endif %}
            </div>
            <div >
                <form action="{% url 'annotation:output_csv' video_name=available_video.video.name|slugify %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Download CSV Data" class='csvdownload'>
                </form>
            </div>

    </div>
</div> 
        {% endif %}
{% endblock %}